//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_prestamo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public int loan_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual loan loan { get; set; }
    }
}
